Використай цей шаблон в роботі з датасетом.      
Ти можеш додавати комірки за потреби, але не змінюй структуру і послідовність питань.      
Обмежся функціями з наведених бібліотек.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

1. Завантаж датасет з бібліотеки seaborn:

In [ ]:
ds=sns.load_dataset('titanic')

2. Переглянь перші рядки датасету. Зроби висновок, чи коректно він завантажився.

In [ ]:
ds.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

3. Перевір типи стовпців. Які з них потребують перетворення?

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

4. Перевір статистику по УСІМ стовпцям датасету.

In [ ]:
ds.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

5. Необхідно створити єдиний стовпчик, що вказує кількість родичів для кожного пасажира на борту, замість:
- кількість братів/сестер або чоловіків/дружин на борту;
- кількість батьків або дітей на борту;

Булева ознака: стовпчик 'alone'=True, якщо пасажир подорожував один (без родичів на борту).        
Перевір, щоб для одиноких пасажирів новий стовпчик мав значення 0.      
Після створення нового стовпчика, дропни "sibsp", "parch", "alone".     
Результат представ у вигляді підрахунку кількості пропущених значень (NaN) у стовпці relatives.

In [ ]:
ds['relatives']=ds['sibsp']+ds['parch']

#if sum(ds.loc[ds['alone'] == True, 'relatives']) == 0:
#    print('Вірно, для пасажирів, в яких "alone"=true, "relatives"=0')
#else:
#    print('Щось не так')

ds.drop(columns= ['sibsp', 'parch', 'alone'])
sum(ds['relatives'].isna())

0

6. Перевір, як часто зустрічається певна кількість родичів в новому стовпці.    
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [ ]:
ds.groupby('relatives')['relatives'].agg(total_passengers='count')

           total_passengers
relatives
0                       537
1                       161
2                       102
3                        29
4                        15
5                        22
6                        12
7                         6
10                        7

7. Використовуючи цикл заміни кількість родичів, що перевищує число 5(п'ять) на значення "above 5"(понад п'ять).       
Запиши значення в новий стовпчик ʼrelatives_categoryʼ.     
Результат представ у вигляді таблиці, побудованої з використанням групування та агрегації:

In [ ]:
ds['relatives_category'] = ds['relatives'].astype(str)

for i in range(len(ds)):
    if ds.loc[i, 'relatives'] > 5:
        ds.loc[i, 'relatives_category'] = 'above 5'

ds.groupby('relatives_category')['relatives_category'].agg(total_category='count')

                    total_category
relatives_category
0                              537
1                              161
2                              102
3                               29
4                               15
5                               22
above 5                         25

8. Необхідно вивести на екран статистику по відсотковому показнику пасажирів з кількістю родичів більше 5 відносно загального числа пасажирів для кожного з міст посадки. Для цього:
- порахуй загальну кількість пасажирів в кожному з міст посадки,
- знайди число пасажирів з кількістю родичів більше 5 в кожному з міст посадки,
- поділи ці два стовчики між собою, перетворивши результат у відсотки (ціле число).        
Відобрази статистику порахованих показників, згруповану по містах посадки.

In [ ]:
stat_city=ds.groupby('embark_town')['embark_town'].agg(total_city='count')
stat_city['above_5_relatives'] = ds[ds['relatives_category'] == 'above 5'].groupby('embark_town')['relatives_category'].agg('count')
stat_city['percentage'] = np.round(stat_city['above_5_relatives'] / stat_city['total_city'] * 100)
stat_city=stat_city.fillna(0)
stat_city

             total_city  above_5_relatives  percentage
embark_town
Cherbourg           168                0.0         0.0
Queenstown           77                0.0         0.0
Southampton         644               25.0         4.0

9. Заповни відсутні значення віку медіаною.

In [ ]:
dscopy=ds.copy()
dscopy.loc[dscopy['age'].isna(), 'age'] = dscopy['age'].median()

10. Створи новий стовпець, де вік представлено категорією, замість числа (наприклад: до 14 років, 14-34 роки, 35-59 років, 60 і більше років). Виконай задачу з використанням користувацької функції. Осіб з невідомим віком познач відповідно.

In [ ]:
def classify_age(age):
    if pd.isna(age):
        return 'unknown'
    elif age < 14:
        return 'child'
    elif age <= 34:
        return 'young'
    elif age <= 59:
        return 'adult'
    else:
        return 'old'

ds['age_group'] = ds['age'].apply(classify_age)
ds.groupby('age_group')['age_group'].agg(total_by_category='count')

           total_by_category
age_group
adult                    210
child                     71
old                       26
unknown                  177
young                    407

11. Перевір, в якій віковій категорії була найвища смертність.     
Для цього рекомендується перетворити стовпець 'alive' в булевий тип.    
 Потім підрахувати загальну кількість пасажирів та кількість тих, хто не вижив.      
 Потім обчисли відносний показниках для кожної категорії.

In [ ]:
ds['not_alive']=ds['alive'] == 'no'
stat_alive=ds.groupby('age_group')['not_alive'].agg(total_group='count')
stat_alive['total_died'] = ds[ds['not_alive'] == True ].groupby('age_group')['not_alive'].agg('count')
stat_alive['death_percentage'] = np.round(stat_alive['total_died'] / stat_alive['total_group'] * 100)
stat_alive

           total_group  total_died  death_percentage
age_group
adult              210         123              59.0
child               71          29              41.0
old                 26          19              73.0
unknown            177         125              71.0
young              407         253              62.0

*Бонусне завдання*         :          
Підготуй розгорнуту статистику смертності по категорії віку, класу квитка, рівню каюти та кількості родичів.      
Які фактори, на твою думку, найбільше пов'язані з рівнем смерності? (наприклад: найбільша смертність у відсотковому значенні спостерігається серед вікової групи ... класу квитка.... при наявності ... родичів та для рівня каюти.... Фактор ... має найвищий вплив на смертність)

In [ ]:
ds['deck'] = ds['deck'].astype(str).replace('nan', 'Unknown')
stat_alive_sorted=stat_alive.sort_values('death_percentage', ascending=False)

st2=ds.groupby('class', observed=False)['not_alive'].agg(class_group='count')
st2['died_by_class'] = ds[ds['not_alive'] == True ].groupby('class', observed=False)['not_alive'].agg('count')
st2['death_percentage2'] = np.round(st2['died_by_class'] / st2['class_group'] * 100)
st2_sorted=st2.sort_values('death_percentage2', ascending=False)

st3=ds.groupby('deck', observed=False)['not_alive'].agg(deck_group='count')
st3['died_by_deck'] = ds[ds['not_alive'] == True ].groupby('deck', observed=False)['not_alive'].agg('count')
st3['death_percentage3'] = np.round(st3['died_by_deck'] / st3['deck_group'] * 100)
st3_sorted=st3.sort_values('death_percentage3', ascending=False)

st4=ds.groupby('relatives_category', observed=False)['not_alive'].agg(rel_group='count')
st4['died_by_rel'] = ds[ds['not_alive'] == True ].groupby('relatives_category', observed=False)['not_alive'].agg('count')
st4['death_percentage4'] = np.round(st4['died_by_rel'] / st4['rel_group'] * 100)
st4_sorted=st4.sort_values('death_percentage4', ascending=False)

print('Stat alive by age:\n', stat_alive_sorted, '\n')
print('Stat alive by class:\n', st2_sorted, '\n')
print('Stat alive by deck:\n', st3_sorted, '\n')
print('Stat alive by relatives_category:\n', st4_sorted, '\n')

Stat alive by age:
            total_group  total_died  death_percentage
age_group
old                 26          19              73.0
unknown            177         125              71.0
young              407         253              62.0
adult              210         123              59.0
child               71          29              41.0

Stat alive by class:
         class_group  died_by_class  death_percentage2
class
Third           491            372               76.0
Second          184             97               53.0
First           216             80               37.0

Stat alive by deck:
          deck_group  died_by_deck  death_percentage3
deck
Unknown         688           482               70.0
A                15             8               53.0
G                 4             2               50.0
C                59            24               41.0
F                13             5               38.0
B                47            12               26.0
E                32             8               25.0
D                33             8               24.0

Stat alive by relatives_category:
                     rel_group  died_by_rel  death_percentage4
relatives_category
5                          22           19               86.0
above 5                    25           21               84.0
4                          15           12               80.0
0                         537          374               70.0
1                         161           72               45.0
2                         102           43               42.0
3                          29            8               28.0

Найбільша смертність у відсотковому значенні спостерігається серед вікової групи 'old' класу квитка 'third' при наявності 5 родичів та для рівня каюти 'A' (якщо опустити невідомі каюти). Фактор великої кількості родичів має найвищий вплив на смертність у відсотках (можливо тому що затонула одразу вся сім'я), але якщо брати кількісно - то найвища смертність у старих та дітей(категорії 'old' та 'young', а також пасажирів 3-го класу (найдешевшого).